### ISSUE TITLE
Add extension to Open VSX Registry

### ISSUE THREAD

**Issue by remusa** [BriteSnow/vscode-toggle-quotes#46] opened 2021-12-31 19:34 UTC
The extension can't be found in [Open VSX Registry](https://open-vsx.org/).

Editors derived from VS Code such as Gitpod and VS Codium cannot access Microsoft's marketplace by policy, so Open VSX is being used as an alternative marketplace.

As a user of Gitpod, Hopefully, I want you to post an extension on open vsx.

Thank you.

**Comment by jeremychone** [comment] 2022-01-04 16:28
Agree, I got multiple requests about this, and this sounds completely. I have a pull request to merge, and then, I work on this one.

**Comment by jeremychone** [comment] 2022-01-04 16:37
duplicate of #33 (closing this occurrence). Definition going to publish to Open VSX Registry. See #33 for tracking.

**Closed by jeremychone** 2022-01-04 16:37 UTC
Labels: duplicate
