### ISSUE TITLE
No longer toggles tilde ( ` )

### ISSUE THREAD

**Issue by mikeerickson** [BriteSnow/vscode-toggle-quotes#12] opened 2018-12-15 20:12 UTC
Not sure when this changed (I have been in Python land for quite a while) but when I returned to work on JS code, the command no longer toggles to tilde ( ` ) character.

It just toggles between single and double quotes.

**Comment by jeremychone** [comment] 2018-12-15 20:17
Can't reproduce this issue. Perhaps your .js files are not set in one of those vscode types: 
https://github.com/BriteSnow/vscode-toggle-quotes/blob/master/package.json#L36

**Comment by mikeerickson** [comment] 2018-12-15 20:32
@jeremychone That was a good lead... It seems my files are defined as `Javascript (Babel)`.  


![image](https://user-images.githubusercontent.com/183153/50047178-47ee3080-0065-11e9-9b03-5d4c91f2a3c0.png)

If I change this to `javascriptreact` it works as expected

![image](https://user-images.githubusercontent.com/183153/50047185-766c0b80-0065-11e9-99a9-a6af7cac9a4a.png)

What is curious though, I have had this `javascript babel` setting for quite sometime.

**Comment by mikeerickson** [comment] 2018-12-15 20:37
There is a VSCode plugin [babel](https://marketplace.visualstudio.com/items?itemName=dzannotti.vscode-babel-coloring) plugin installed which causes the "Javascript (babel)" setting to appear, but it still assumes file is "javascript"

Further, if I remove the plugin, then it displays as "Javascript" but it still does not work

![image](https://user-images.githubusercontent.com/183153/50047222-22155b80-0066-11e9-9872-3da2342da94b.png)

**Comment by mikeerickson** [comment] 2018-12-15 20:42
I have adjusted `settings.json` as follows and things are now working, but I think this is a "hack" per se as the defaults from your extension should do the trick.  As you can see, VSCode does not like this setting, and your documentation to adjust `configurationDefaults` section doesnt even exist

![image](https://user-images.githubusercontent.com/183153/50047255-b8e21800-0066-11e9-9912-993e3f26f73e.png)

**Comment by mikeerickson** [comment] 2018-12-15 20:45
I am going to leave the `settings.json` update and roll from here, but I still think there is something that needs to be resolved.

**Comment by jeremychone** [comment] 2018-12-15 21:12
Great, glad it works now. 

However, I agree that it is strange that you  have to reset `[javascript]` config in your own user settings (with the  same value of the default plugin value) to make it work. Perhaps try a full VSCode reload or restart, this is the only thing that comes to mind now. 

About the "green" underline in the settings, this is a known VSCode schema validation limitation, where VSCode does not recognize language specific plugin properties. I do not think it can be fixed on the toggle plugin side, and having a per-language way to customize is definitely a must.

**Comment by mikeerickson** [comment] 2018-12-15 22:52
I have done the full reload, Restart VSCode song and dance 🤓 

As far as configurationDefaults object in settings, it does not exist at all.  When I get back to coding (likely tomorrow) I will test this as well.

**Comment by jeremychone** [comment] 2018-12-25 05:16
From the comments above, I am going to close this one. If there is something (like the doc/readme)  missing, feel free to enter another ticket or even a pull request.

**Closed by jeremychone** 2018-12-25 05:16 UTC
Labels: CANT_REPRODUCE
