### ISSUE TITLE
can't change quote from '' / "" to ``

### ISSUE THREAD

**Issue by tjx666** [BriteSnow/vscode-toggle-quotes#18] opened 2019-08-08 16:30 UTC
Question as title.
I can only toggle quote from single to double, but can't toggle to ``.

OS: Mojave 10.14.3
vscode version:  1.36.1

**Comment by jeremychone** [comment] 2019-08-08 20:59
Which file you are doing this?

**Comment by tjx666** [comment] 2019-08-09 07:48
javascript file...

**Comment by jeremychone** [comment] 2019-08-09 15:44
There are some configuration defaults for which the \` is included: 
https://github.com/BriteSnow/vscode-toggle-quotes/blob/master/package.json#L36

So, perhaps your javascript file get categorized by VSCode as a variant (like `javascriptreact`) that does not match the list above, and therefore fall back to the single to double quotes only cycle.

**Comment by tjx666** [comment] 2019-08-09 16:04
<img width="1440" alt="Snipaste_2019-08-10_00-02-05" src="https://user-images.githubusercontent.com/41773861/62792584-2f55ed80-bb02-11e9-83b1-10d20599b387.png">

**Comment by tjx666** [comment] 2019-08-09 16:05
vs code of the latest version still has this problem.

**Comment by jeremychone** [comment] 2019-08-09 16:34
Weird, could not reproduce this in 1.36.x, and I just updated to 1.37, and it works. There is something weird here.

**Comment by mmirus** [comment] 2019-08-19 19:09
Same issue here - let me know how I can help with debugging. :)

**Comment by jeremychone** [comment] 2019-08-19 20:40
My biggest issue is that I cannot reproduce this issue. I have version  1.37.1 on Mac.

**Comment by jeremychone** [comment] 2019-08-19 20:42
Please, check #12, it seems to have been a similar issue.

**Comment by mmirus** [comment] 2019-08-20 15:43
Hmm, when I changed it from JavaScript to JavaScript React it started working. Changing back to vanilla JavaScript breaks it again. Using the setting described in https://github.com/BriteSnow/vscode-toggle-quotes/issues/12#issuecomment-447596479 also fixes it, but it's weird that it's necessary.

I'm on VS Code 1.37.1 on Windows (using WSL via the remote development system).

**Comment by oren-l** [comment] 2020-04-15 18:29
Also happens for me but only in my linux laptop (kubuntu 18.04) vscode v1.44.1

Adding the following to my `settings.json` solved it:
```javascript
"[javascript]": {
    "togglequotes.chars": [
        "\"",
        "'",
        "`"
    ]
}
```

**Comment by jeremychone** [comment] 2020-04-15 18:56
Thanks for the note. I did not manage to reproduce it, but I do not have a Linux laptop handy.

**Comment by jeremychone** [comment] 2022-01-04 16:41
closing as cannot reproduce and quite old. Feel free to reopen.

**Closed by jeremychone** 2022-01-04 16:41 UTC
Labels: investigate
